# Generated by Django 4.2.20 on 2025-12-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='plaintext',
            field=models.BooleanField(default=False),
        ),
    ]
