# Generated by Django 4.2.20 on 2025-09-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_entry_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='archival_media/'),
        ),
    ]
