# Generated by Django 4.2.20 on 2025-12-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_entry_plaintext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='plaintext',
            new_name='plain_text',
        ),
    ]
