# Generated by Django 4.2.20 on 2025-09-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_entry_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='ai_slop',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='media/journal'),
        ),
    ]
