# Generated by Django 4.2.20 on 2026-08-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_rename_plaintext_entry_plain_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
