# Generated by Django 4.2.20 on 2025-09-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_entry_ai_slop_alter_entry_media_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='source_url',
        ),
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
