# Generated by Django 4.2.20 on 2025-09-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_remove_entry_source_url_entry_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_type',
            field=models.CharField(choices=[('journal', 'Diary Entry'), ('comment', 'Encyclopedia Entry'), ('archival', 'Archival Comment')], default='journal', max_length=20),
        ),
    ]
