# Generated by Django 4.2.20 on 2025-09-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_alter_entry_options_entry_is_hidden_entry_is_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
