# Generated by Django 4.2.20 on 2026-01-05 09:09

import batchai.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextInferenceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=batchai.models.uuid_string, max_length=36, unique=True)),
                ('priority', models.IntegerField(default=50)),
                ('purpose', models.TextField(blank=True)),
                ('system_prompt', models.TextField(blank=True)),
                ('user_prompt', models.TextField()),
                ('llm_model', models.TextField(choices=[('gemma-3-27B', 'gemma-3-27B'), ('Kimi-K2', 'Kimi-K2'), ('QwenLong-L1.5-30B-A3B', 'QwenLong-L1.5-30B-A3B')], default='gemma-3-27B')),
                ('temperature', models.FloatField(default=0.3)),
                ('max_tokens', models.IntegerField(default=4000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('llama_cpp_extra_arguments', models.TextField(blank=True)),
                ('worker', models.TextField(blank=True, default=None, null=True, verbose_name='The machine that has taken the job')),
                ('result', models.TextField(blank=True, default='')),
                ('logs', models.TextField(blank=True, default='')),
                ('secrets', models.TextField(blank=True, default='')),
                ('status', models.IntegerField(default=0)),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='batchai_tex_status_f9b384_idx'), models.Index(fields=['status', 'priority'], name='batchai_tex_status_daf974_idx'), models.Index(fields=['status', 'priority', 'created'], name='batchai_tex_status_2aca14_idx'), models.Index(fields=['created'], name='batchai_tex_created_abb631_idx'), models.Index(fields=['priority'], name='batchai_tex_priorit_501f89_idx'), models.Index(fields=['result'], name='batchai_tex_result_2d14cc_idx'), models.Index(fields=['requester'], name='batchai_tex_request_7e18ef_idx')],
            },
        ),
    ]
