# Generated by Django 4.2.20 on 2026-01-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textinferencerequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'STATUS_PENDING'), (10, 'STATUS_LOCKED'), (99, 'STATUS_FINALIZED_LINE'), (100, 'STATUS_DONE'), (101, 'STATUS_CANCELLED'), (102, 'STATUS_ERROR')], default=0),
        ),
    ]
