# Generated by Django 4.2.20 on 2026-02-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchai', '0002_alter_textinferencerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textinferencerequest',
            name='llm_model',
            field=models.TextField(default='gemma-3-27B'),
        ),
    ]
