# Potentially common libs

from functools import wraps
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

# 🤖 Generated by Qwen3.5 27B
def require_secret_cookie(cookie_name, cookie_value, redirect_template=None):
    """
    Decorator that requires a specific cookie to be present with a specific value.

    Args:
        cookie_name (str): The name of the cookie to check.
        cookie_value (str): The expected value of the cookie.
        redirect_template (str, optional): Path to a template to render if the check fails.
                                          If None, defaults to redirecting to '/login' or raising an error.

    Returns:
        Decorated function.
    """
    def decorator(view_func):
        @wraps(view_func)
        def wrapper(request, *args, **kwargs):
            # Check if the cookie exists and matches the value
            # request.COOKIES returns a dict-like object
            actual_value = request.COOKIES.get(cookie_name)

            if actual_value == cookie_value:
                # Cookie is valid, proceed to the view
                return view_func(request, *args, **kwargs)
            else:
                # Cookie is missing or invalid

                # If a specific template was provided, render it
                if redirect_template:
                    # You might want to pass context, e.g., error messages
                    return render(request, redirect_template, status=403)

                # Fallback behavior if no template is specified
                # Option A: Redirect to a standard login/protected page
                # return HttpResponseRedirect(reverse('login'))

                # Option B: Render a generic error page (common fallback)
                return render(request, '403.html', status=403)

        return wrapper
    return decorator

